parameters:
    mbx_abstract_entity_manager.class: Mbx\SymfonyBootstrapBundle\Abstracts\AbstractEntityManager
    mbx.twig_extension.class: Mbx\SymfonyBootstrapBundle\Twig\MbxTwigExtension

services:
    mbx_abstract_entity_manager:
        abstract: true
        class: '%mbx_abstract_entity_manager.class%'
        arguments: ['@doctrine.orm.entity_manager']
    mbx_abstract_form_handler:
        abstract: true
        arguments: ['@form.factory', '@request', '@router']
    mbx.twig_extension:
        class: '%mbx.twig_extension.class%'
        arguments: ['@service_container']
    #   public: false
        tags:
            - { name: twig.extension }