parameters:
    mbx.abstract_entity_manager.class: Mbx\ArchitectBundle\Abstracts\AbstractEntityManager
    mbx.twig_extension.class: Mbx\ArchitectBundle\Twig\MbxTwigExtension

services:
    mbx.abstract_entity_manager:
        abstract: true
        class: '%mbx.abstract_entity_manager.class%'
        arguments: ['@doctrine.orm.entity_manager']
        autowire: true
    mbx.abstract_form_handler:
        abstract: true
        autowire: true
        arguments: ['@form.factory', '@request_stack', '@router']
    mbx.twig_extension:
        class: '%mbx.twig_extension.class%'
        arguments: ['@service_container']
    #   public: false
        tags:
            - { name: twig.extension }