parameters:
    mbx_abstract_entity_manager.class: Mbx\SymfonyBootstrapBundle\Abstracts\AbstractEntityManager

services:
    mbx_abstract_entity_manager:
        abstract: true
        class: '%mbx_abstract_entity_manager.class%'
        arguments: ['@doctrine.orm.entity_manager']
    mbx_abstract_form_handler:
        abstract: true
        arguments: ['@form.factory', '@request', '@router']
